#!/usr/bin/env node
/**
 * Neo Agents AI — Dashboard Server
 * Serves the dashboard on localhost only.
 * Reads .ai-agents/ live from the project root.
 *
 * Usage:
 *   node server.js --port=7842 --root=/path/to/user/project
 */

const http = require("http");
const fs   = require("fs");
const path = require("path");
const url  = require("url");

/* ── Args ── */
const args = Object.fromEntries(
  process.argv.slice(2).map(a => {
    const [k, v] = a.replace(/^--/, "").split("=");
    return [k, v];
  })
);

const PORT         = parseInt(args.port || process.env.NEO_PORT || 7842, 10);
const PROJECT_ROOT = args.root || process.env.NEO_ROOT || process.cwd();
const AGENTS_DIR   = path.join(PROJECT_ROOT, ".ai-agents");
const DOCS_DIR     = path.join(AGENTS_DIR, "docs");
const TASKS_FILE   = path.join(AGENTS_DIR, "tasks.json");
const CONFIG_FILE  = path.join(AGENTS_DIR, "config.json");
const DASHBOARD    = path.join(__dirname, "dist", "index.html");
const DIST_DIR     = path.join(__dirname, "dist");

/* ── Access token ── */
// Read from the project config generated by /neo:setup.
// If missing, API routes are still served but without token protection.
let ACCESS_TOKEN = null;
try {
  const cfg = JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8"));
  if (cfg && cfg.access_token) ACCESS_TOKEN = cfg.access_token;
} catch {
  // Config not yet created — token enforcement skipped until setup runs.
}

/* ── MIME ── */
const MIME = {
  ".html": "text/html",
  ".js":   "application/javascript",
  ".css":  "text/css",
  ".json": "application/json",
  ".md":   "text/plain; charset=utf-8",
  ".png":  "image/png",
  ".svg":  "image/svg+xml",
};

/* ── Helpers ── */
function readJSON(filePath) {
  try { return JSON.parse(fs.readFileSync(filePath, "utf8")); }
  catch { return null; }
}

function send(res, status, body, type = "application/json") {
  res.writeHead(status, {
    "Content-Type": type,
    "Access-Control-Allow-Origin": "http://localhost:" + PORT,
  });
  res.end(typeof body === "string" ? body : JSON.stringify(body));
}

function listDir(dirPath) {
  try {
    return fs.readdirSync(dirPath)
      .filter(f => f.endsWith(".md") && !f.startsWith("."))
      .sort((a, b) => b.localeCompare(a)); // newest first
  } catch { return []; }
}

function checkToken(query, res) {
  if (!ACCESS_TOKEN) return true; // not enforced until setup runs
  if (query.token !== ACCESS_TOKEN) {
    send(res, 401, { error: "Unauthorized. Missing or invalid token." });
    return false;
  }
  return true;
}

/* ── Route handlers ── */
const routes = {

  // GET /api/config
  "/api/config": (req, res, query) => {
    if (!checkToken(query, res)) return;
    // Re-read token on each config fetch so it stays current after setup re-run.
    const config = readJSON(CONFIG_FILE);
    if (!config) return send(res, 404, { error: "config.json not found. Run /neo:setup first." });
    send(res, 200, config);
  },

  // GET /api/tasks
  "/api/tasks": (req, res, query) => {
    if (!checkToken(query, res)) return;
    const data = readJSON(TASKS_FILE);
    send(res, 200, data || { tasks: [] });
  },

  // GET /api/docs  → { BA: ["file.md", ...], SA: [...], ... }
  "/api/docs": (req, res, query) => {
    if (!checkToken(query, res)) return;
    const agentDirs = ["BA", "SA", "DS", "DEV", "PM", "SPEC"];
    const result = {};
    for (const dir of agentDirs) {
      result[dir] = listDir(path.join(DOCS_DIR, dir));
    }
    send(res, 200, result);
  },

  // GET /api/doc?path=.ai-agents/docs/BA/2026-05-27-xxx.md&token=...
  "/api/doc": (req, res, query) => {
    if (!checkToken(query, res)) return;
    const relPath = query.path;
    if (!relPath) return send(res, 400, { error: "path required" });

    // Security: only allow files inside .ai-agents/docs/
    const abs = path.resolve(PROJECT_ROOT, relPath);
    if (!abs.startsWith(path.resolve(DOCS_DIR))) {
      return send(res, 403, { error: "forbidden" });
    }

    try {
      const content = fs.readFileSync(abs, "utf8");
      send(res, 200, content, "text/plain; charset=utf-8");
    } catch {
      send(res, 404, "Document not found.", "text/plain");
    }
  },

  // GET /api/timeline
  "/api/timeline": (req, res, query) => {
    if (!checkToken(query, res)) return;
    const data  = readJSON(TASKS_FILE);
    const tasks = (data && data.tasks) ? data.tasks : [];
    const total = tasks.length;

    const PHASE_DEFS = [
      { num: "1", label: "Build v1",  column: "Backlog"     },
      { num: "2", label: "Test",      column: "In Progress" },
      { num: "3", label: "v2 Agents", column: "Review"      },
      { num: "4", label: "Scale",     column: "Done"        },
    ];

    const colCounts = {};
    for (const def of PHASE_DEFS) colCounts[def.column] = 0;
    for (const t of tasks) {
      if (t.column in colCounts) colCounts[t.column]++;
    }

    const phases = PHASE_DEFS.map((def, idx) => {
      const count = colCounts[def.column];
      const pct   = total > 0 ? Math.round((count / total) * 100) : 0;

      // "done" if this column is empty but later ones have tasks (work moved past)
      // "active" if this column currently has tasks
      // "upcoming" if this column is empty and all later columns are too
      const laterHasTasks = PHASE_DEFS.slice(idx + 1).some(d => colCounts[d.column] > 0);
      const state = count > 0 ? "active" : (laterHasTasks ? "done" : "upcoming");

      // derive a display date from the most recently updated task in this column
      const colTasks = tasks.filter(t => t.column === def.column && t.updated_at);
      let dates = "";
      if (colTasks.length > 0) {
        const latest = new Date(Math.max(...colTasks.map(t => new Date(t.updated_at).getTime())));
        dates = latest.toLocaleDateString("en-US", { month: "short", year: "numeric" });
      }

      return { num: def.num, label: def.label, state, dates, pct };
    });

    const COLUMN_STATUS = {
      "Backlog":     "upcoming",
      "In Progress": "active",
      "Review":      "active",
      "Done":        "done",
    };
    const COLUMN_PHASE = { "Backlog": 1, "In Progress": 2, "Review": 3, "Done": 4 };

    const milestones = tasks.map(t => ({
      id:     t.id,
      title:  t.title,
      phase:  COLUMN_PHASE[t.column] ?? 1,
      date:   t.updated_at
        ? new Date(t.updated_at).toLocaleDateString("en-US", { month: "short", year: "numeric" })
        : (t.date ?? ""),
      agent:  t.agent ?? "",
      status: COLUMN_STATUS[t.column] ?? "upcoming",
    }));

    send(res, 200, { phases, milestones });
  },

  // POST /api/task/create  { title, column? }
  "/api/task/create": (req, res, query) => {
    if (!checkToken(query, res)) return;
    let body = "";
    req.on("data", d => body += d);
    req.on("end", () => {
      try {
        const { title, column } = JSON.parse(body);
        if (!title || typeof title !== "string" || !title.trim()) {
          return send(res, 400, { error: "title is required" });
        }
        const validColumns = ["Backlog", "In Progress", "Review", "Done"];
        const targetColumn = validColumns.includes(column) ? column : "Backlog";

        const slug = title.trim().toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/^-+|-+$/g, "");
        const today = new Date();
        const yyyymmdd = today.getFullYear().toString() +
          String(today.getMonth() + 1).padStart(2, "0") +
          String(today.getDate()).padStart(2, "0");
        const id = `${slug}-${yyyymmdd}`;

        const newTask = {
          id,
          title: title.trim(),
          status: "🔲 not started",
          column: targetColumn,
          agent: "",
          created_at: today.toISOString(),
          updated_at: today.toISOString(),
          steps: {
            ba:  "🔲 not started",
            sa:  "🔲 not started",
            ds:  "🔲 not started",
            dev: "🔲 not started",
          },
          docs: { ba_doc: "", sa_doc: "", ds_doc: "", dev_doc: "", spec_doc: "" },
        };

        const data = readJSON(TASKS_FILE) || { tasks: [] };
        data.tasks.push(newTask);
        fs.writeFileSync(TASKS_FILE, JSON.stringify(data, null, 2), "utf8");
        send(res, 200, { ok: true, task: newTask });
      } catch (e) {
        send(res, 500, { error: e.message });
      }
    });
  },

  // POST /api/task/move  { id, column, token }
  "/api/task/move": (req, res, query) => {
    if (!checkToken(query, res)) return;
    let body = "";
    req.on("data", d => body += d);
    req.on("end", () => {
      try {
        const { id, column } = JSON.parse(body);
        const valid = ["Backlog", "In Progress", "Review", "Done"];
        if (!valid.includes(column)) return send(res, 400, { error: "Invalid column" });

        const data = readJSON(TASKS_FILE);
        if (!data) return send(res, 404, { error: "tasks.json not found" });

        const task = data.tasks.find(t => t.id === id);
        if (!task) return send(res, 404, { error: "task not found" });

        task.column  = column;
        task.status  = column === "Done" ? "✅ done" : column === "In Progress" ? "⏳ in progress" : column;
        task.updated_at = new Date().toISOString();

        fs.writeFileSync(TASKS_FILE, JSON.stringify(data, null, 2), "utf8");
        send(res, 200, { ok: true });
      } catch (e) {
        send(res, 500, { error: e.message });
      }
    });
  },

  // GET / → dashboard (no token required — token is in URL for JS to read)
  "/": (req, res) => {
    try {
      const html = fs.readFileSync(DASHBOARD, "utf8");
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(html);
    } catch {
      send(res, 500, "Dashboard not found. Run `pnpm build` in packages/dashboard first.", "text/plain");
    }
  },
};

/* ── Server ── */
const server = http.createServer((req, res) => {
  const parsed   = new URL(req.url, `http://localhost:${PORT}`);
  const pathname = parsed.pathname;
  const query    = Object.fromEntries(parsed.searchParams);

  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    res.writeHead(204, { "Access-Control-Allow-Origin": "http://localhost:" + PORT });
    return res.end();
  }

  const handler = routes[pathname];
  if (handler) return handler(req, res, query);

  // Static files — serve from dist/ (Vite build output)
  const ext  = path.extname(pathname);
  const mime = MIME[ext] || "text/plain";
  const abs  = path.join(DIST_DIR, pathname);
  if (fs.existsSync(abs)) {
    try {
      const content = fs.readFileSync(abs);
      res.writeHead(200, { "Content-Type": mime });
      res.end(content);
      return;
    } catch {}
  }

  send(res, 404, { error: "not found" });
});

// Bind to 127.0.0.1 only — never exposed externally
server.listen(PORT, "127.0.0.1", () => {
  const tokenSuffix = ACCESS_TOKEN ? `?token=${ACCESS_TOKEN}` : "";
  console.log(`\n✅ Neo Agents dashboard running`);
  console.log(`   URL:     http://localhost:${PORT}${tokenSuffix}`);
  console.log(`   Project: ${PROJECT_ROOT}`);
  if (!ACCESS_TOKEN) {
    console.log(`\n   ⚠️  No access token found. Run /neo:setup to enable token protection.`);
  }
  console.log(`\nPress Ctrl+C to stop.\n`);
});

server.on("error", (e) => {
  if (e.code === "EADDRINUSE") {
    console.error(`\n❌ Port ${PORT} is in use. Try --port=${PORT + 1}`);
  } else {
    console.error("\n❌ Server error:", e.message);
  }
  process.exit(1);
});
